server:
  port: 8000
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://EMPLOYEESERVICE
        predicates:
        - Path=/employees/**
      - id: testModule
        uri: lb://TESTSERVICE
        predicates:
        - Path=/test/**